//
// Person.swift
// SwiftyRestAPI
//
// Autogenerated by SwifyRestAPI
// Created with love by Icalia Labs
//

import Foundation

struct Person: Codable {

    let lastName: String
    let age: Int
    let height: Double
    let firstName: String
    let isAdult: Bool

}