//
// UserService.swift
// SwiftyRestAPI
//
// Autogenerated by SwifyRestAPI
// Created with love by Icalia Labs
//

import Foundation
import Requestr

protocol UserService {

    func aPIKeyOwner(completion: @escaping (ApiResult<APIKeyOwner>) -> Void)

}

class UserApiService {

    let apiClient: ApiClient

    init(apiClient: ApiClient) {
        self.apiClient = apiClient
    }

}


extension UserApiService: UserService {

    func aPIKeyOwner(completion: @escaping (ApiResult<APIKeyOwner>) -> Void) {
        let endpoint = Endpoint.aPIKeyOwner
        apiClient.GET(endpoint.fullPath) { (result) in
            completion(Result(apiResult: result))
        }
    }

}
