extension APIGenerator {
 
    public func makeEndpointsFile() -> FileText {
      return """
      \(makeHeader(fileName: "Endpoints.swift"))

      enum Endpoint {

      \(makeBaseURL(with: basePath))

      \(makeEnumCases(for: allEndpoints))

      \(makeFullPathComputedProperty(for: allEndpoints))

      }

      """
  }

  private func makeBaseURL(with baseURL: String) -> String {
      return """
          static let baseURL = "\(baseURL)"
      """
  }

  private func makeEnumCases(for endpoints: [API.Endpoint]) -> String {
      var string = ""
      for endpoint in endpoints {
          string += """
              case \(endpoint.name)

          """
      }
      return String(string.dropLast())
  }

  private func makeFullPathComputedProperty(for endpoints: [API.Endpoint]) -> String {
      var string = ""
      string += """
          var fullPath: String {
              let path: String
              switch self {

      """
      for endpoint in endpoints {
          string += """
                      case .\(endpoint.name):
                          path = "\(endpoint.relativePath)"

          """
      }
      string += """
              }
              return Endpoint.baseURL + path
          }
      """
      return string
  }

  func makeHeader(fileName: String) -> String {
      return  """
      //
      // \(fileName)
      // SwiftyRestAPI
      //
      // Autogenerated by SwifyRestAPI
      // Created with love by Icalia Labs
      //
      """
  }

}
