import Foundation

final class AlamofireAPIGenerator: APIGenerator {

    private let api: API

    lazy var basePath: String = {
        return api.basePath
    }()

    lazy var allEndpoints: [API.Endpoint] = {
        return api.categories.flatMap { $0.endpoints }
    }()

    // MARK: - API Generator

    init(api: API) {
        self.api = api
    }

    // MARK: Helper's

    private func makeHeader(fileName: String) -> String {
        return  """
        //
        // \(fileName)
        // SwiftyRestAPI
        //
        // Autogenerated by SwifyRestAPI
        // Created with love by Icalia Labs
        //
        """
    }
}

// MARK: - Endpoints File

extension AlamofireAPIGenerator {

    func makeEndpointsFile() -> FileText {
        return """
        \(makeHeader(fileName: "Endpoints.swift"))

        enum Endpoint {

        \(makeBaseURL(with: basePath))

        \(makeEnumCases(for: allEndpoints))

        \(makeFullPathComputedProperty(for: allEndpoints))

        }

        """
    }

    // MARK:  Helper's

    private func makeBaseURL(with baseURL: String) -> String {
        return """
            static let baseURL = "\(baseURL)"
        """
    }

    private func makeEnumCases(for endpoints: [API.Endpoint]) -> String {
        var string = ""
        for endpoint in endpoints {
            string += """
                case \(endpoint.name)

            """
        }
        return String(string.dropLast())
    }

    private func makeFullPathComputedProperty(for endpoints: [API.Endpoint]) -> String {
        var string = ""
        string += """
            var fullPath: String {
                let path: String
                switch self {

        """
        for endpoint in endpoints {
            string += """
                        case .\(endpoint.name):
                            path = "\(endpoint.relativePath)"

            """
        }
        string += """
                }
                return Endpoint.baseURL + path
            }
        """
        return string
    }

}

// MARK: - Service Files

extension AlamofireAPIGenerator {

    func makeServiceFiles() -> [FileText] {
        return api.categories.map(makeServiceFile)
    }

    private func makeServiceFile(for category: API.Category) -> FileText {
        return """
        \(makeHeader(fileName: fileName(for: category)))

        import Foundation
        import Alamofire

        \(makeServiceProtocol(for: category))

        \(makeServiceApiClass(for: category))

        \(makeProtocolImplementationExtension(for: category))

        """
    }

    // MARK: Helper's

    private func fileName(for category: API.Category) -> String {
        return "\(category.name)Service.swift"
    }

    private func protocolName(for category: API.Category) -> String {
        return "\(category.name)Service"
    }

    private func className(for category: API.Category) -> String {
        return "\(category.name)ApiService"
    }

    private func methodSignatureForEndpoint(_ endpoint: API.Endpoint) -> String {
        var resourceName = endpoint.resourceName
        if endpoint.isResourceArray {
            resourceName.insert("[", at: resourceName.startIndex)
            resourceName.insert("]", at: resourceName.endIndex)
        }
        return "func \(endpoint.name)(completion: @escaping (\(resourceName)) -> Void)"
    }

    private func makeServiceProtocol(for category: API.Category) -> String {
        return """
        protocol \(protocolName(for: category)) {

        \(makeServiceProtocolMethods(for: category))

        }
        """
    }

    private func makeServiceProtocolMethods(for category: API.Category) -> String {
        var string = ""
        for endpoint in category.endpoints {
            string += """
                \(methodSignatureForEndpoint(endpoint))


            """
        }
        return String(string.dropLast().dropLast())
    }

    private func makeServiceApiClass(for category: API.Category) -> String {
        return """
        class \(className(for: category)) {

            let apiClient: ApiClient

            init(apiClient: ApiClient) {
                self.apiClient = apiClient
            }

        }

        """
    }

    private func makeProtocolImplementationExtension(for category: API.Category) -> String {
        return """
        extension \(className(for: category)): \(protocolName(for: category)) {

        \(makeProtocolImplementationExtensionMethods(for: category))

        }
        """
    }

    private func makeProtocolImplementationExtensionMethods(for category: API.Category) -> String {
        var string = ""
        for endpoint in category.endpoints {
          let resourceName = endpoint.resourceName
            string += """
                \(methodSignatureForEndpoint(endpoint)) {
                    let endpoint = Endpoint.\(endpoint.name)

                    Alamofire.request(endpoint.fullPath, method: .\(endpoint.method.rawValue.lowercased())).response { response in
                        let decoder = JSONDecoder()
                        let \(resourceName.lowercased()) = try decoder.decode(\(resourceName).self, from: response)
                        completion(\(resourceName.lowercased()))
                    }
                }


            """
        }
        return String(string.dropLast().dropLast())
    }

}
