# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# platform :osx, '10.12'

target 'SwiftyMac' do
  use_frameworks!

  pod 'SwiftyRestAPI', :path => '../'

  target 'SwiftyMacTests' do
    inherit! :search_paths
  end

  target 'SwiftyMacUITests' do
    inherit! :search_paths
  end

end
