
target 'SwiftyMac' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'SwiftyRestAPI',:path => '../'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == '<insert target name of your pod here>'
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '3.0'
              end
          end
      end
  end
  
end
