//
//  ModelGenerationExtension.swift
//  SwiftyRestAPIPackageDescription
//
//  Created by Jorge Elizondo on 10/16/17.
//

import Foundation

public extension ModelGenerator {
    
    func findType(value: Any) -> Type {
        let type: Type
        
        switch value {
        case is Bool:
            type = .boolean
        case is Int:
            type = .int
        case is Double:
            type = .double
        case is String:
            type = .string
        case let array as [Any]:
            type = .array(findType(value: array[0]))
        case is [String : Any]:
            type = .dictionary
        case is NSNull:
            type = .null
        default:
            type = .unknown
        }
        return type
    }
    
    func makeHeader(fileName: String) -> String {
        return  """
        //
        // \(fileName)
        // SwiftyRestAPI
        //
        // Autogenerated by SwifyRestAPI
        // Created with love by Icalia Labs
        //
        """
    }

}
